name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    if: github.actor != 'PJBot' && github.actor != 'FrontierATC' && github.actor != 'LOPBot'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
